version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "study-assistant"
resolve_s3 = true
s3_prefix = "study-assistant"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BedrockModelId=ap.amazon.nova-lite-v1:0"
disable_rollback = true
